//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import org.hl7.v3.AllInfrastructureRootTemplateId;
import org.hl7.v3.AllInfrastructureRootTypeId;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for COCT_MT230100UV.Approval complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="COCT_MT230100UV.Approval"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/&gt;
 *         &lt;element name="id" type="{urn:ihe:pharm}II"/&gt;
 *         &lt;element name="code" type="{urn:ihe:pharm}CD" minOccurs="0"/&gt;
 *         &lt;element name="statusCode" type="{urn:ihe:pharm}CS" minOccurs="0"/&gt;
 *         &lt;element name="holder" type="{urn:ihe:pharm}COCT_MT230100UV.Holder" minOccurs="0"/&gt;
 *         &lt;element name="author" type="{urn:ihe:pharm}COCT_MT230100UV.Author"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nullFlavor" type="{urn:ihe:pharm}NullFlavor" /&gt;
 *       &lt;attribute name="classCode" use="required" type="{urn:ihe:pharm}ActClassContract" /&gt;
 *       &lt;attribute name="moodCode" use="required" type="{urn:ihe:pharm}ActMoodEventOccurrence" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COCT_MT230100UV.Approval", propOrder = {
        "realmCodes",
        "typeId",
        "templateIds",
        "id",
        "code",
        "statusCode",
        "holder",
        "author"
})
public class COCTMT230100UVApproval {

    @XmlElement(name = "realmCode", namespace = "urn:hl7-org:v3")
    protected List<org.hl7.v3.CS> realmCodes;
    @XmlElement(namespace = "urn:hl7-org:v3")
    protected AllInfrastructureRootTypeId typeId;
    @XmlElement(name = "templateId", namespace = "urn:hl7-org:v3")
    protected List<AllInfrastructureRootTemplateId> templateIds;
    @XmlElement(required = true)
    protected Id id;
    protected CD code;
    protected ihe.pharm.CS statusCode;
    @XmlElementRef(name = "holder", namespace = "urn:ihe:pharm", type = JAXBElement.class, required = false)
    protected JAXBElement<COCTMT230100UVHolder> holder;
    @XmlElement(required = true)
    protected COCTMT230100UVAuthor author;
    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavors;
    @XmlAttribute(name = "classCode", required = true)
    protected String classCode;
    @XmlAttribute(name = "moodCode", required = true)
    protected ActMoodEventOccurrence moodCode;

    /**
     * Gets the value of the realmCodes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCodes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCodes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.hl7.v3.CS }
     */
    public List<org.hl7.v3.CS> getRealmCodes() {
        if (realmCodes == null) {
            realmCodes = new ArrayList<org.hl7.v3.CS>();
        }
        return this.realmCodes;
    }

    /**
     * Gets the value of the typeId property.
     *
     * @return possible object is
     * {@link AllInfrastructureRootTypeId }
     */
    public AllInfrastructureRootTypeId getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     *
     * @param value allowed object is
     *              {@link AllInfrastructureRootTypeId }
     */
    public void setTypeId(AllInfrastructureRootTypeId value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateIds property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateIds property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateIds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllInfrastructureRootTemplateId }
     */
    public List<AllInfrastructureRootTemplateId> getTemplateIds() {
        if (templateIds == null) {
            templateIds = new ArrayList<AllInfrastructureRootTemplateId>();
        }
        return this.templateIds;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link Id }
     */
    public Id getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link Id }
     */
    public void setId(Id value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link CD }
     */
    public CD getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link CD }
     */
    public void setCode(CD value) {
        this.code = value;
    }

    /**
     * Gets the value of the statusCode property.
     *
     * @return possible object is
     * {@link ihe.pharm.CS }
     */
    public ihe.pharm.CS getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     *
     * @param value allowed object is
     *              {@link ihe.pharm.CS }
     */
    public void setStatusCode(ihe.pharm.CS value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the holder property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link COCTMT230100UVHolder }{@code >}
     */
    public JAXBElement<COCTMT230100UVHolder> getHolder() {
        return holder;
    }

    /**
     * Sets the value of the holder property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link COCTMT230100UVHolder }{@code >}
     */
    public void setHolder(JAXBElement<COCTMT230100UVHolder> value) {
        this.holder = value;
    }

    /**
     * Gets the value of the author property.
     *
     * @return possible object is
     * {@link COCTMT230100UVAuthor }
     */
    public COCTMT230100UVAuthor getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     *
     * @param value allowed object is
     *              {@link COCTMT230100UVAuthor }
     */
    public void setAuthor(COCTMT230100UVAuthor value) {
        this.author = value;
    }

    /**
     * Gets the value of the nullFlavors property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavors property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavors().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getNullFlavors() {
        if (nullFlavors == null) {
            nullFlavors = new ArrayList<String>();
        }
        return this.nullFlavors;
    }

    /**
     * Gets the value of the classCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setClassCode(String value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     *
     * @return possible object is
     * {@link ActMoodEventOccurrence }
     */
    public ActMoodEventOccurrence getMoodCode() {
        return moodCode;
    }

    /**
     * Sets the value of the moodCode property.
     *
     * @param value allowed object is
     *              {@link ActMoodEventOccurrence }
     */
    public void setMoodCode(ActMoodEventOccurrence value) {
        this.moodCode = value;
    }

}
