//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import org.hl7.v3.AllInfrastructureRootTemplateId;
import org.hl7.v3.AllInfrastructureRootTypeId;
import org.hl7.v3.CS;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for COCT_MT440001UV.ValuedItem complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="COCT_MT440001UV.ValuedItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/&gt;
 *         &lt;element name="id" type="{urn:ihe:pharm}II" maxOccurs="unbounded"/&gt;
 *         &lt;element name="code" type="{urn:ihe:pharm}CD" minOccurs="0"/&gt;
 *         &lt;element name="effectiveTime" type="{urn:ihe:pharm}IVL_TS" minOccurs="0"/&gt;
 *         &lt;element name="unitQuantity" type="{urn:ihe:pharm}RTO_PQ_PQ" minOccurs="0"/&gt;
 *         &lt;element name="unitPriceAmt" type="{urn:ihe:pharm}RTO_MO_PQ"/&gt;
 *         &lt;element name="netAmt" type="{urn:ihe:pharm}MO" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="classCode" use="required" type="{urn:ihe:pharm}ActClassInvoiceElement" /&gt;
 *       &lt;attribute name="moodCode" use="required" type="{urn:ihe:pharm}x_ActMoodDefEvn" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COCT_MT440001UV.ValuedItem", propOrder = {
        "realmCodes",
        "typeId",
        "templateIds",
        "ids",
        "code",
        "effectiveTime",
        "unitQuantity",
        "unitPriceAmt",
        "netAmt"
})
public class COCTMT440001UVValuedItem {

    @XmlElement(name = "realmCode", namespace = "urn:hl7-org:v3")
    protected List<CS> realmCodes;
    @XmlElement(namespace = "urn:hl7-org:v3")
    protected AllInfrastructureRootTypeId typeId;
    @XmlElement(name = "templateId", namespace = "urn:hl7-org:v3")
    protected List<AllInfrastructureRootTemplateId> templateIds;
    @XmlElement(name = "id", required = true)
    protected List<Id> ids;
    protected CD code;
    protected IVLTS effectiveTime;
    protected RTOPQPQ unitQuantity;
    @XmlElement(required = true)
    protected RTOMOPQ unitPriceAmt;
    protected MO netAmt;
    @XmlAttribute(name = "classCode", required = true)
    protected ActClassInvoiceElement classCode;
    @XmlAttribute(name = "moodCode", required = true)
    protected XActMoodDefEvn moodCode;

    /**
     * Gets the value of the realmCodes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCodes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCodes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     */
    public List<CS> getRealmCodes() {
        if (realmCodes == null) {
            realmCodes = new ArrayList<CS>();
        }
        return this.realmCodes;
    }

    /**
     * Gets the value of the typeId property.
     *
     * @return possible object is
     * {@link AllInfrastructureRootTypeId }
     */
    public AllInfrastructureRootTypeId getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     *
     * @param value allowed object is
     *              {@link AllInfrastructureRootTypeId }
     */
    public void setTypeId(AllInfrastructureRootTypeId value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateIds property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateIds property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateIds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllInfrastructureRootTemplateId }
     */
    public List<AllInfrastructureRootTemplateId> getTemplateIds() {
        if (templateIds == null) {
            templateIds = new ArrayList<AllInfrastructureRootTemplateId>();
        }
        return this.templateIds;
    }

    /**
     * Gets the value of the ids property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ids property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Id }
     */
    public List<Id> getIds() {
        if (ids == null) {
            ids = new ArrayList<Id>();
        }
        return this.ids;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link CD }
     */
    public CD getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link CD }
     */
    public void setCode(CD value) {
        this.code = value;
    }

    /**
     * Gets the value of the effectiveTime property.
     *
     * @return possible object is
     * {@link IVLTS }
     */
    public IVLTS getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * Sets the value of the effectiveTime property.
     *
     * @param value allowed object is
     *              {@link IVLTS }
     */
    public void setEffectiveTime(IVLTS value) {
        this.effectiveTime = value;
    }

    /**
     * Gets the value of the unitQuantity property.
     *
     * @return possible object is
     * {@link RTOPQPQ }
     */
    public RTOPQPQ getUnitQuantity() {
        return unitQuantity;
    }

    /**
     * Sets the value of the unitQuantity property.
     *
     * @param value allowed object is
     *              {@link RTOPQPQ }
     */
    public void setUnitQuantity(RTOPQPQ value) {
        this.unitQuantity = value;
    }

    /**
     * Gets the value of the unitPriceAmt property.
     *
     * @return possible object is
     * {@link RTOMOPQ }
     */
    public RTOMOPQ getUnitPriceAmt() {
        return unitPriceAmt;
    }

    /**
     * Sets the value of the unitPriceAmt property.
     *
     * @param value allowed object is
     *              {@link RTOMOPQ }
     */
    public void setUnitPriceAmt(RTOMOPQ value) {
        this.unitPriceAmt = value;
    }

    /**
     * Gets the value of the netAmt property.
     *
     * @return possible object is
     * {@link MO }
     */
    public MO getNetAmt() {
        return netAmt;
    }

    /**
     * Sets the value of the netAmt property.
     *
     * @param value allowed object is
     *              {@link MO }
     */
    public void setNetAmt(MO value) {
        this.netAmt = value;
    }

    /**
     * Gets the value of the classCode property.
     *
     * @return possible object is
     * {@link ActClassInvoiceElement }
     */
    public ActClassInvoiceElement getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     *
     * @param value allowed object is
     *              {@link ActClassInvoiceElement }
     */
    public void setClassCode(ActClassInvoiceElement value) {
        this.classCode = value;
    }

    /**
     * Gets the value of the moodCode property.
     *
     * @return possible object is
     * {@link XActMoodDefEvn }
     */
    public XActMoodDefEvn getMoodCode() {
        return moodCode;
    }

    /**
     * Sets the value of the moodCode property.
     *
     * @param value allowed object is
     *              {@link XActMoodDefEvn }
     */
    public void setMoodCode(XActMoodDefEvn value) {
        this.moodCode = value;
    }

}
