//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import org.hl7.v3.AllInfrastructureRootTemplateId;
import org.hl7.v3.AllInfrastructureRootTypeId;
import org.hl7.v3.CS;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for COCT_MT230100UV.SpecializedKind complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="COCT_MT230100UV.SpecializedKind"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{urn:hl7-org:v3}InfrastructureRootElements"/&gt;
 *         &lt;element name="code" type="{urn:ihe:pharm}CE" minOccurs="0"/&gt;
 *         &lt;element name="generalizedMedicineClass" type="{urn:ihe:pharm}COCT_MT230100UV.MedicineClass" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nullFlavor" type="{urn:ihe:pharm}NullFlavor" /&gt;
 *       &lt;attribute name="classCode" use="required" type="{urn:ihe:pharm}RoleClassIsSpeciesEntity" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "COCT_MT230100UV.SpecializedKind", propOrder = {
        "realmCodes",
        "typeId",
        "templateIds",
        "code",
        "generalizedMedicineClass"
})
public class COCTMT230100UVSpecializedKind {

    @XmlElement(name = "realmCode", namespace = "urn:hl7-org:v3")
    protected List<CS> realmCodes;
    @XmlElement(namespace = "urn:hl7-org:v3")
    protected AllInfrastructureRootTypeId typeId;
    @XmlElement(name = "templateId", namespace = "urn:hl7-org:v3")
    protected List<AllInfrastructureRootTemplateId> templateIds;
    protected CE code;
    @XmlElementRef(name = "generalizedMedicineClass", namespace = "urn:ihe:pharm", type = JAXBElement.class, required = false)
    protected JAXBElement<COCTMT230100UVMedicineClass> generalizedMedicineClass;
    @XmlAttribute(name = "nullFlavor")
    protected List<String> nullFlavors;
    @XmlAttribute(name = "classCode", required = true)
    protected RoleClassIsSpeciesEntity classCode;

    /**
     * Gets the value of the realmCodes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the realmCodes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRealmCodes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CS }
     */
    public List<CS> getRealmCodes() {
        if (realmCodes == null) {
            realmCodes = new ArrayList<CS>();
        }
        return this.realmCodes;
    }

    /**
     * Gets the value of the typeId property.
     *
     * @return possible object is
     * {@link AllInfrastructureRootTypeId }
     */
    public AllInfrastructureRootTypeId getTypeId() {
        return typeId;
    }

    /**
     * Sets the value of the typeId property.
     *
     * @param value allowed object is
     *              {@link AllInfrastructureRootTypeId }
     */
    public void setTypeId(AllInfrastructureRootTypeId value) {
        this.typeId = value;
    }

    /**
     * Gets the value of the templateIds property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the templateIds property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTemplateIds().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllInfrastructureRootTemplateId }
     */
    public List<AllInfrastructureRootTemplateId> getTemplateIds() {
        if (templateIds == null) {
            templateIds = new ArrayList<AllInfrastructureRootTemplateId>();
        }
        return this.templateIds;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link CE }
     */
    public CE getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link CE }
     */
    public void setCode(CE value) {
        this.code = value;
    }

    /**
     * Gets the value of the generalizedMedicineClass property.
     *
     * @return possible object is
     * {@link JAXBElement }{@code <}{@link COCTMT230100UVMedicineClass }{@code >}
     */
    public JAXBElement<COCTMT230100UVMedicineClass> getGeneralizedMedicineClass() {
        return generalizedMedicineClass;
    }

    /**
     * Sets the value of the generalizedMedicineClass property.
     *
     * @param value allowed object is
     *              {@link JAXBElement }{@code <}{@link COCTMT230100UVMedicineClass }{@code >}
     */
    public void setGeneralizedMedicineClass(JAXBElement<COCTMT230100UVMedicineClass> value) {
        this.generalizedMedicineClass = value;
    }

    /**
     * Gets the value of the nullFlavors property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullFlavors property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullFlavors().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     */
    public List<String> getNullFlavors() {
        if (nullFlavors == null) {
            nullFlavors = new ArrayList<String>();
        }
        return this.nullFlavors;
    }

    /**
     * Gets the value of the classCode property.
     *
     * @return possible object is
     * {@link RoleClassIsSpeciesEntity }
     */
    public RoleClassIsSpeciesEntity getClassCode() {
        return classCode;
    }

    /**
     * Sets the value of the classCode property.
     *
     * @param value allowed object is
     *              {@link RoleClassIsSpeciesEntity }
     */
    public void setClassCode(RoleClassIsSpeciesEntity value) {
        this.classCode = value;
    }

}
