//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * A code for a common (periodical) activity of daily
 * living based on which the event related periodic
 * interval is specified.
 *
 *
 * <p>Java class for EIVL.event complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EIVL.event"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{urn:ihe:pharm}CE"&gt;
 *       &lt;attribute name="code" type="{urn:ihe:pharm}TimingEvent" /&gt;
 *       &lt;attribute name="codeSystem" type="{urn:ihe:pharm}uid" fixed="2.16.840.1.113883.5.139" /&gt;
 *       &lt;attribute name="codeSystemName" type="{urn:ihe:pharm}st" fixed="TimingEvent" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EIVL.event")
public class EIVLEvent
        extends CE {


}
