//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for GLIST_TS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="GLIST_TS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:ihe:pharm}ANY"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="head" type="{urn:ihe:pharm}TS"/&gt;
 *         &lt;element name="increment" type="{urn:ihe:pharm}PQ"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="period" type="{urn:ihe:pharm}int" /&gt;
 *       &lt;attribute name="denominator" type="{urn:ihe:pharm}int" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GLIST_TS", propOrder = {
        "head",
        "increment"
})
public class GLISTTS
        extends ANY {

    @XmlElement(required = true)
    protected TS head;
    @XmlElement(required = true)
    protected PQ increment;
    @XmlAttribute(name = "period")
    protected BigInteger period;
    @XmlAttribute(name = "denominator")
    protected BigInteger denominator;

    /**
     * Gets the value of the head property.
     *
     * @return possible object is
     * {@link TS }
     */
    public TS getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     *
     * @param value allowed object is
     *              {@link TS }
     */
    public void setHead(TS value) {
        this.head = value;
    }

    /**
     * Gets the value of the increment property.
     *
     * @return possible object is
     * {@link PQ }
     */
    public PQ getIncrement() {
        return increment;
    }

    /**
     * Sets the value of the increment property.
     *
     * @param value allowed object is
     *              {@link PQ }
     */
    public void setIncrement(PQ value) {
        this.increment = value;
    }

    /**
     * Gets the value of the period property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setPeriod(BigInteger value) {
        this.period = value;
    }

    /**
     * Gets the value of the denominator property.
     *
     * @return possible object is
     * {@link BigInteger }
     */
    public BigInteger getDenominator() {
        return denominator;
    }

    /**
     * Sets the value of the denominator property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setDenominator(BigInteger value) {
        this.denominator = value;
    }

}
