//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package ihe.pharm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonNamePartAffixTypes.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PersonNamePartAffixTypes"&gt;
 *   &lt;restriction base="{urn:ihe:pharm}cs"&gt;
 *     &lt;enumeration value="AC"/&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="VV"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 */
@XmlType(name = "PersonNamePartAffixTypes")
@XmlEnum
public enum PersonNamePartAffixTypes {

    AC,
    NB,
    PR,
    VV;

    public String value() {
        return name();
    }

    public static PersonNamePartAffixTypes fromValue(String v) {
        return valueOf(v);
    }

}
