//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UVP_TS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UVP_TS"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:hl7-org:v3}TS"&gt;
 *       &lt;attribute name="probability" type="{urn:hl7-org:v3}probability" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UVP_TS")
public class UVPTS
        extends TS {

    @XmlAttribute(name = "probability")
    protected Double probability;

    /**
     * Gets the value of the probability property.
     *
     * @return possible object is
     * {@link Double }
     */
    public Double getProbability() {
        return probability;
    }

    /**
     * Sets the value of the probability property.
     *
     * @param value allowed object is
     *              {@link Double }
     */
    public void setProbability(Double value) {
        this.probability = value;
    }

}
