package pl.konczak.nzoz.ereceptaapp;

import org.apache.commons.codec.binary.Base64;
import org.apache.cxf.helpers.IOUtils;
import org.apache.cxf.message.Message;
import org.apache.wss4j.dom.WSConstants;
import pl.gov.csioz.p1.erecepta.mt.v20170510.PakietReceptMT;
import pl.gov.csioz.p1.erecepta.mt.v20170510.ReceptaMT;
import pl.gov.csioz.p1.erecepta.mt.v20170510.ReceptyMT;
import pl.gov.csioz.p1.erecepta.ws.v20170510.ZapisPakietuReceptRequest;
import pl.gov.csioz.p1.wspolne.mt.v20170510.IdentyfikatorZadaniaMT;

import javax.xml.soap.SOAPMessage;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

@Component
public class ZapisPakietuReceptRequestFactory {

    @Value("classpath:recepta.xml")
    private Resource receptaxml;

    @Value("classpath:base64.txt")
    private Resource base64;

    // SOAPMessage.CHARACTER_SET_ENCODING
    // Message.PROTOCOL_HEADERS
    public ZapisPakietuReceptRequest create() throws Exception {
        ZapisPakietuReceptRequest zapisPakietuReceptRequest = new ZapisPakietuReceptRequest();

        PakietReceptMT pakietRecept = new PakietReceptMT();

        ReceptyMT recepty = new ReceptyMT();

        ReceptaMT recepta = new ReceptaMT();
        recepta.setIdentyfikatorDokumentuWPakiecie(1);
        // String sample = "bazinga";
        // byte[] sampleBytes = sample.getBytes("UTF-8");
        // byte[] sampleInBase64 = Base64.encodeBase64(sampleBytes);
        // String sampleInBase64AsString = new String(sampleInBase64, Charset.forName("UTF-8"));
        // System.out.println(sampleInBase64AsString);
        // byte[] sampleDecodeBase64 = Base64.decodeBase64(sampleInBase64AsString.getBytes());
        // String sampleDecodeBase64String = new String(sampleDecodeBase64);
        // System.out.println(sampleDecodeBase64String);
        // String restoredSample = new String(sampleBytes, Charset.forName("UTF-8"));
        // System.out.println(restoredSample);
        InputStream inputStream = receptaxml.getInputStream();
        // String s = IOUtils.toString(inputStream, "UTF-8");
        // System.out.println(s);
        // System.out.println(s.);
        // byte[] bytes = IOUtils.readBytesFromStream(inputStream);

        // String text = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48P3htbC1zdHlsZXNoZWV0IGhyZWY9IkNEQV9QTF9JR18xLjMuMS54c2wiIHR5cGU9InRleHQveHNsIj8+PENsaW5pY2FsRG9jdW1lbnQgeG1sbnM9InVybjpobDctb3JnOnYzIiB4bWxuczpleHRQTD0iaHR0cDovL3d3dy5jc2lvei5nb3YucGwveHNkL2V4dFBML3IyIiB4bWxuczpwaGFybT0idXJuOmloZTpwaGFybSIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9ImV4dFBMOkNsaW5pY2FsRG9jdW1lbnQiPgogICAgPCEtLSBEb2t1bWVudCByZWNlcHR5IG5hIGxlayBPVEMtLT4KICAgIDx0eXBlSWQgZXh0ZW5zaW9uPSJQT0NEX0hEMDAwMDQwIiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4xLjMiLz4KICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjEuMy42LjEuNC4xLjE5Mzc2LjEuOS4xLjEuMSIvPgogICAgPHRlbXBsYXRlSWQgcm9vdD0iMS4zLjYuMS40LjEuMTkzNzYuMS41LjMuMS4xLjEiLz4KICAgIDx0ZW1wbGF0ZUlkIGV4dGVuc2lvbj0iMS4zLjEiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC4xLjMiLz4KICAgIDxpZCBkaXNwbGF5YWJsZT0idHJ1ZSIgZXh0ZW5zaW9uPSIzQ0MxRUFGQTcwNkM0MzQ4QkE0NDcxIiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMi43LjIwMS4yLjEiLz4KICAgIDxjb2RlIGNvZGU9IjU3ODMzLTYiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjYuMSIgY29kZVN5c3RlbU5hbWU9IkxPSU5DIiBkaXNwbGF5TmFtZT0iUHJlc2NyaXB0aW9uIGZvciBtZWRpY2F0aW9uIERvY3VtZW50Ij4KICAgICAgICA8dHJhbnNsYXRpb24gY29kZT0iMDQuMDEiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMS4xLjMyIiBjb2RlU3lzdGVtTmFtZT0iS0xBU19ET0tfUDEiIGRpc3BsYXlOYW1lPSJSZWNlcHRhIj4KICAgICAgICAgICAgPHF1YWxpZmllcj4KICAgICAgICAgICAgICAgIDxuYW1lIGNvZGU9IktETEVLIiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuNS4xIiBjb2RlU3lzdGVtTmFtZT0iUG9sc2tpZUtsYXN5ZmlrYXRvcnlITDd2MyIgZGlzcGxheU5hbWU9IkthdGVnb3JpYSBkb3N0xJlwbm/Fm2NpIGxla3UiLz4KICAgICAgICAgICAgICAgIDx2YWx1ZSBjb2RlPSJScCIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjExLjEuMjUiLz4KICAgICAgICAgICAgPC9xdWFsaWZpZXI+CiAgICAgICAgICAgIDxxdWFsaWZpZXI+CiAgICAgICAgICAgICAgICA8bmFtZSBjb2RlPSJSTEVLIiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuNS4xIiBjb2RlU3lzdGVtTmFtZT0iUG9sc2tpZUtsYXN5ZmlrYXRvcnlITDd2MyIgZGlzcGxheU5hbWU9IlJvZHphaiBsZWt1Ii8+CiAgICAgICAgICAgICAgICA8dmFsdWUgY29kZT0iRyIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjUuMSIgZGlzcGxheU5hbWU9IkxlayBnb3Rvd3kiLz4KICAgICAgICAgICAgPC9xdWFsaWZpZXI+CiAgICAgICAgICAgIDxxdWFsaWZpZXI+CiAgICAgICAgICAgICAgICA8bmFtZSBjb2RlPSJUV1JFQyIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjUuMSIgY29kZVN5c3RlbU5hbWU9IlBvbHNraWVLbGFzeWZpa2F0b3J5SEw3djMiIGRpc3BsYXlOYW1lPSJUcnliIHd5c3Rhd2llbmlhIHJlY2VwdHkiLz4KICAgICAgICAgICAgICAgIDx2YWx1ZSBjb2RlPSJaIiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuNS4xIiBkaXNwbGF5TmFtZT0iWnd5a8WCYSIvPgogICAgICAgICAgICA8L3F1YWxpZmllcj4KICAgICAgICAgICAgPHF1YWxpZmllcj4KICAgICAgICAgICAgICAgIDxuYW1lIGNvZGU9IlRSUkVDIiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuNS4xIiBjb2RlU3lzdGVtTmFtZT0iUG9sc2tpZUtsYXN5ZmlrYXRvcnlITDd2MyIgZGlzcGxheU5hbWU9IlRyeWIgcmVhbGl6YWNqaSByZWNlcHR5Ii8+CiAgICAgICAgICAgICAgICA8dmFsdWUgY29kZT0iWiIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjUuMSIgZGlzcGxheU5hbWU9Ilp3eWvFgnkiLz4KICAgICAgICAgICAgPC9xdWFsaWZpZXI+CiAgICAgICAgPC90cmFuc2xhdGlvbj4KICAgIDwvY29kZT4KICAgIDx0aXRsZT5SZWNlcHRhPC90aXRsZT4KICAgIDxlZmZlY3RpdmVUaW1lIHZhbHVlPSIyMDE5MDcyNzA5MTU0MCIvPgogICAgPGNvbmZpZGVudGlhbGl0eUNvZGUgY29kZT0iTiIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuNS4yNSIvPgogICAgPGxhbmd1YWdlQ29kZSBjb2RlPSJwbC1QTCIvPgogICAgPHNldElkIGV4dGVuc2lvbj0iNDMyMjMxIiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuNy4yLjIiLz4KICAgIDx2ZXJzaW9uTnVtYmVyIHZhbHVlPSIxIi8+CiAgICA8cmVjb3JkVGFyZ2V0PgogICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC4yLjIzIi8+CiAgICAgICAgPHBhdGllbnRSb2xlPgogICAgICAgICAgICA8aWQgZGlzcGxheWFibGU9ImZhbHNlIiBleHRlbnNpb249IjEyMzQ1IiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMi43LjAuMTcuMSIvPgogICAgICAgICAgICA8aWQgZGlzcGxheWFibGU9InRydWUiIGV4dGVuc2lvbj0iNjQwMTA1OTU4ODgiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xLjEuNjE2Ii8+CiAgICAgICAgICAgIDxhZGRyPgogICAgICAgICAgICAgICAgPGNvdW50cnk+UG9sc2thPC9jb3VudHJ5PgogICAgICAgICAgICAgICAgPHBvc3RhbENvZGUgcG9zdENpdHk9IlBpYXNlY3pubyIgeHNpOnR5cGU9ImV4dFBMOmFkeHAucG9zdGFsQ29kZSI+MDMtMTM0PC9wb3N0YWxDb2RlPgogICAgICAgICAgICAgICAgPGNpdHk+V2Fyc3phd2E8L2NpdHk+CiAgICAgICAgICAgICAgICA8c3RyZWV0TmFtZT5PZGtyeXRhPC9zdHJlZXROYW1lPgogICAgICAgICAgICAgICAgPGhvdXNlTnVtYmVyPjQxPC9ob3VzZU51bWJlcj4KICAgICAgICAgICAgICAgIDx1bml0SUQ+MTI8L3VuaXRJRD4KICAgICAgICAgICAgICAgIDxjZW5zdXNUcmFjdD5URVJZVCBTSU1DOiA5ODc2NTQ8L2NlbnN1c1RyYWN0PgogICAgICAgICAgICA8L2FkZHI+CiAgICAgICAgICAgIDxwYXRpZW50PgogICAgICAgICAgICAgICAgPG5hbWU+CiAgICAgICAgICAgICAgICAgICAgPGdpdmVuPkphbjwvZ2l2ZW4+CiAgICAgICAgICAgICAgICAgICAgPGdpdmVuPkZyYW5jaXN6ZWs8L2dpdmVuPgogICAgICAgICAgICAgICAgICAgIDxmYW1pbHk+S293YWxza2k8L2ZhbWlseT4KICAgICAgICAgICAgICAgIDwvbmFtZT4KICAgICAgICAgICAgICAgIDxhZG1pbmlzdHJhdGl2ZUdlbmRlckNvZGUgY29kZT0iTSIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuNS4xIi8+CiAgICAgICAgICAgICAgICA8YmlydGhUaW1lIHZhbHVlPSIxOTYyMDkxNSIvPgogICAgICAgICAgICA8L3BhdGllbnQ+CiAgICAgICAgPC9wYXRpZW50Um9sZT4KICAgIDwvcmVjb3JkVGFyZ2V0PgogICAgPGF1dGhvcj4KICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuMTAuMi44MiIvPgogICAgICAgIDxmdW5jdGlvbkNvZGUgY29kZT0iTEVLIiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTEuMy4xOCIgZGlzcGxheU5hbWU9Ikxla2FyeiIvPgogICAgICAgIDx0aW1lIHZhbHVlPSIyMDE3MTAxMiIvPgogICAgICAgIDxhc3NpZ25lZEF1dGhvcj4KICAgICAgICAgICAgPGlkIGRpc3BsYXlhYmxlPSJ0cnVlIiBleHRlbnNpb249IjczOTEyMDgiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xLjYuMiIvPgogICAgICAgICAgICA8YXNzaWduZWRQZXJzb24+CiAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuMTAuMi4xIi8+CiAgICAgICAgICAgICAgICA8bmFtZT4KICAgICAgICAgICAgICAgICAgICA8Z2l2ZW4+QWRhbTwvZ2l2ZW4+CiAgICAgICAgICAgICAgICAgICAgPGZhbWlseT5Lb3dhbHNraTwvZmFtaWx5PgogICAgICAgICAgICAgICAgPC9uYW1lPgogICAgICAgICAgICA8L2Fzc2lnbmVkUGVyc29uPgogICAgICAgICAgICA8cmVwcmVzZW50ZWRPcmdhbml6YXRpb24+CiAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuMTAuMi4xNyIvPgogICAgICAgICAgICAgICAgPGlkIGRpc3BsYXlhYmxlPSJ0cnVlIiBleHRlbnNpb249IjAwMDAwMDkyNjU3OC0wMDEiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4yLjMuMiIvPgogICAgICAgICAgICAgICAgPG5hbWU+UG9yYWRuaWEgUE9aPC9uYW1lPgogICAgICAgICAgICAgICAgPHRlbGVjb20gdXNlPSJQVUIiIHZhbHVlPSJ0ZWw6MjItMTExMTEyMyIvPgogICAgICAgICAgICAgICAgPGFkZHI+CiAgICAgICAgICAgICAgICAgICAgPHBvc3RhbENvZGU+MDAtMTg0PC9wb3N0YWxDb2RlPgogICAgICAgICAgICAgICAgICAgIDxjaXR5PldhcnN6YXdhPC9jaXR5PgogICAgICAgICAgICAgICAgICAgIDxzdHJlZXROYW1lPnVsLiBEdWJvaXM8L3N0cmVldE5hbWU+CiAgICAgICAgICAgICAgICAgICAgPGhvdXNlTnVtYmVyPjVBPC9ob3VzZU51bWJlcj4KICAgICAgICAgICAgICAgIDwvYWRkcj4KICAgICAgICAgICAgICAgIDxhc09yZ2FuaXphdGlvblBhcnRPZj4KICAgICAgICAgICAgICAgICAgICA8d2hvbGVPcmdhbml6YXRpb24+CgkJCQkJCTwhLS0gUmVnb24gcHJ6ZWRzacSZYmlvcnN0d2EgLS0+CiAgICAgICAgICAgICAgICAgICAgICAgIDxpZCBkaXNwbGF5YWJsZT0idHJ1ZSIgZXh0ZW5zaW9uPSI4NDA5NDc4MzUwMDAwNCIgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjIuMi4yIi8+CiAgICAgICAgICAgICAgICAgICAgICAgIDxhc09yZ2FuaXphdGlvblBhcnRPZj4KCQkJCQkJPCEtLSBwb2RtaW90IC0gbnIga3NpZWdpICsgcmVnb24gcG9kbWlvdHUgLS0+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8d2hvbGVPcmdhbml6YXRpb24+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGlkIGRpc3BsYXlhYmxlPSJ0cnVlIiBleHRlbnNpb249IjAwMDAwMDkyNjU3OCIgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjIuMy4xIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPCEtLSA8aWQgZXh0ZW5zaW9uPSIxMjM0NTY3ODkiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4yLjIuMSIgZGlzcGxheWFibGU9InRydWUiLz4gLS0+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3dob2xlT3JnYW5pemF0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICA8L2FzT3JnYW5pemF0aW9uUGFydE9mPgogICAgICAgICAgICAgICAgICAgIDwvd2hvbGVPcmdhbml6YXRpb24+CiAgICAgICAgICAgICAgICA8L2FzT3JnYW5pemF0aW9uUGFydE9mPgogICAgICAgICAgICA8L3JlcHJlc2VudGVkT3JnYW5pemF0aW9uPgogICAgICAgIDwvYXNzaWduZWRBdXRob3I+CiAgICA8L2F1dGhvcj4KICAgIDxjdXN0b2RpYW4+CiAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjEwLjIuMjAiLz4KICAgICAgICA8YXNzaWduZWRDdXN0b2RpYW4+CiAgICAgICAgICAgIDxyZXByZXNlbnRlZEN1c3RvZGlhbk9yZ2FuaXphdGlvbj4KICAgICAgICAgICAgICAgIDxpZCBhc3NpZ25pbmdBdXRob3JpdHlOYW1lPSJDU0lPWiIgZGlzcGxheWFibGU9ImZhbHNlIiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQiLz4KICAgICAgICAgICAgPC9yZXByZXNlbnRlZEN1c3RvZGlhbk9yZ2FuaXphdGlvbj4KICAgICAgICA8L2Fzc2lnbmVkQ3VzdG9kaWFuPgogICAgPC9jdXN0b2RpYW4+CiAgICA8bGVnYWxBdXRoZW50aWNhdG9yPgogICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC4yLjYiLz4KICAgICAgICA8dGltZSB2YWx1ZT0iMjAxNzEwMTIiLz4KICAgICAgICA8c2lnbmF0dXJlQ29kZSBjb2RlPSJTIi8+CiAgICAgICAgPGFzc2lnbmVkRW50aXR5PgogICAgICAgICAgICA8aWQgZGlzcGxheWFibGU9InRydWUiIGV4dGVuc2lvbj0iNzM5MTIwOCIgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEuNi4yIi8+CiAgICAgICAgPC9hc3NpZ25lZEVudGl0eT4KICAgIDwvbGVnYWxBdXRoZW50aWNhdG9yPgogICAgPGNvbXBvbmVudD4KICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMTMuMTAuMi4yNSIvPgogICAgICAgIDxzdHJ1Y3R1cmVkQm9keT4KICAgICAgICAgICAgPGNvbXBvbmVudD4KICAgICAgICAgICAgICAgIDxzZWN0aW9uPgogICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjEuMy42LjEuNC4xLjE5Mzc2LjEuOS4xLjIuMSIvPgogICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC4zLjQiLz4KICAgICAgICAgICAgICAgICAgICA8aWQgZXh0ZW5zaW9uPSI0MzIxIiByb290PSIyLjE2Ljg0MC4xLjExMzg4My4zLjQ0MjQuMi43LjIwMS4yLjQiLz4KICAgICAgICAgICAgICAgICAgICA8Y29kZSBjb2RlPSI1NzgyOC02IiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My42LjEiIGNvZGVTeXN0ZW1OYW1lPSJMT0lOQyIgZGlzcGxheU5hbWU9IlByZXNjcmlwdGlvbnMiLz4KICAgICAgICAgICAgICAgICAgICA8dGl0bGU+UnAuPC90aXRsZT4KICAgICAgICAgICAgICAgICAgICA8dGV4dD4KICAgICAgICAgICAgICAgICAgICAgICAgPHBhcmFncmFwaCBJRD0iU0JBRE1fMSI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBab2ZyYW4gPGJyLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDEgb3AuIHBvIDYwIHRhYmwuPGJyLz4gCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBPZHDFgmF0bm/Fm8SHOiAxMDAlPGJyLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIEQuUy4gMSB4IDEgdGFibC4gcmFubwogICAgICAgICAgICAgICAgICAgICAgICA8L3BhcmFncmFwaD4KICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICAgICAgPGVudHJ5PgogICAgICAgICAgICAgICAgICAgICAgICA8c3Vic3RhbmNlQWRtaW5pc3RyYXRpb24gY2xhc3NDb2RlPSJTQkFETSIgbW9vZENvZGU9IklOVCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIxLjMuNi4xLjQuMS4xOTM3Ni4xLjkuMS4zLjIiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjEwLjIwLjEuMjQiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjEuMy42LjEuNC4xLjE5Mzc2LjEuNS4zLjEuNC43Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIxLjMuNi4xLjQuMS4xOTM3Ni4xLjkuMS4zLjYiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjEuMy42LjEuNC4xLjE5Mzc2LjEuNS4zLjEuNC43LjEiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC40LjMiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpZCBleHRlbnNpb249IjNDQzFFQUZBNzA2QzQzNDhCQTQ0NzEtMSIgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjIuNy4yMDEuMi4zIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGV4dD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cmVmZXJlbmNlIHZhbHVlPSIjU0JBRE1fMSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC90ZXh0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPHN0YXR1c0NvZGUgY29kZT0iY29tcGxldGVkIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8ZWZmZWN0aXZlVGltZSB4c2k6dHlwZT0iSVZMX1RTIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bG93IHZhbHVlPSIyMDE3MTAxMiIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxoaWdoIG51bGxGbGF2b3I9Ik5BIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2VmZmVjdGl2ZVRpbWU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cmVwZWF0TnVtYmVyIHZhbHVlPSIxIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y29uc3VtYWJsZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8bWFudWZhY3R1cmVkUHJvZHVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMTAuMjAuMS41MyIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIxLjMuNi4xLjQuMS4xOTM3Ni4xLjUuMy4xLjQuNy4yIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxtYW51ZmFjdHVyZWRNYXRlcmlhbD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjEuMy42LjEuNC4xLjE5Mzc2LjEuOS4xLjMuMSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjEwLjQuNTQiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjb2RlIGNvZGU9IjkwMDAwMDAxNCIgY29kZVN5c3RlbT0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjYuMSIgZGlzcGxheU5hbWU9IlpvZnJhbiIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG5hbWU+Wm9mcmFuPC9uYW1lPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHBoYXJtOmFzQ29udGVudCBjbGFzc0NvZGU9IkNPTlQiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwaGFybTpjb250YWluZXJQYWNrYWdlZE1lZGljaW5lIGNsYXNzQ29kZT0iQ09OVCIgZGV0ZXJtaW5lckNvZGU9IklOU1RBTkNFIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHBoYXJtOmNvZGUgY29kZT0iMDk5MDk5OTEwMjM2NTIiIGNvZGVTeXN0ZW09IjEuMy4xNjAiIGNvZGVTeXN0ZW1OYW1lPSJHUzEiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHBoYXJtOm5hbWU+Wm9yZmFuPC9waGFybTpuYW1lPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cGhhcm06Zm9ybUNvZGUgY29kZT0iMzAwNjYwMDAiIGNvZGVTeXN0ZW09IjAuNC4wLjEyNy4wLjE2LjEuMS4yLjEiIGRpc3BsYXlOYW1lPSJUYWJsZXQgY29udGFpbmVyIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwaGFybTpjYXBhY2l0eVF1YW50aXR5IHZhbHVlPSI2MCIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvcGhhcm06Y29udGFpbmVyUGFja2FnZWRNZWRpY2luZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvcGhhcm06YXNDb250ZW50PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L21hbnVmYWN0dXJlZE1hdGVyaWFsPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbWFudWZhY3R1cmVkUHJvZHVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvY29uc3VtYWJsZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxlbnRyeVJlbGF0aW9uc2hpcCB0eXBlQ29kZT0iQ09NUCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHN1cHBseSBjbGFzc0NvZGU9IlNQTFkiIG1vb2RDb2RlPSJSUU8iPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIxLjMuNi4xLjQuMS4xOTM3Ni4xLjkuMS4zLjgiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjEwLjQuNTUiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGVmZmVjdGl2ZVRpbWUgdmFsdWU9IjIwMTkwNzI3MDkxNTQwIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpbmRlcGVuZGVudEluZCB2YWx1ZT0iZmFsc2UiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHF1YW50aXR5IHZhbHVlPSIxIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwcm9kdWN0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG1hbnVmYWN0dXJlZFByb2R1Y3Q+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG1hbnVmYWN0dXJlZExhYmVsZWREcnVnPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y29kZSBjb2RlPSIwOTkwOTk5MTAyMzY1MiIgY29kZVN5c3RlbT0iMS4zLjE2MCIgY29kZVN5c3RlbU5hbWU9IkdTMSIgZGlzcGxheU5hbWU9IlBvbG9jYXJkIDE1MG1nICg2MCB0YWJsLikiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L21hbnVmYWN0dXJlZExhYmVsZWREcnVnPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9tYW51ZmFjdHVyZWRQcm9kdWN0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3Byb2R1Y3Q+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zdXBwbHk+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2VudHJ5UmVsYXRpb25zaGlwPgogICAgICAgICAgICAgICAgICAgICAgICA8L3N1YnN0YW5jZUFkbWluaXN0cmF0aW9uPgogICAgICAgICAgICAgICAgICAgIDwvZW50cnk+CiAgICAgICAgICAgICAgICA8L3NlY3Rpb24+CiAgICAgICAgICAgIDwvY29tcG9uZW50PgogICAgICAgICAgICA8Y29tcG9uZW50PgogICAgICAgICAgICAgICAgPHNlY3Rpb24+CiAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMTAuMjAuMS45Ii8+CiAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMS4zLjYuMS40LjEuMTkzNzYuMS41LjMuMS4xLjUuMy43Ii8+CiAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjEwLjMuNjkiLz4KICAgICAgICAgICAgICAgICAgICA8Y29kZSBjb2RlPSI0ODc2OC02IiBjb2RlU3lzdGVtPSIyLjE2Ljg0MC4xLjExMzg4My42LjEiLz4KICAgICAgICAgICAgICAgICAgICA8dGl0bGU+RGFuZSBvIHViZXpwaWVjemVuaXUgaSB1cHJhd25pZW5pYWNoPC90aXRsZT4KICAgICAgICAgICAgICAgICAgICA8dGV4dD4KICAgICAgICAgICAgICAgICAgICAgICAgPHBhcmFncmFwaCBJRD0iQUNUXzIiPiBPZGR6aWHFgiBORlo6IDA3IDxici8+IFVwcmF3bmllbmlhIGRvZGF0a293ZTogWksgKE5yIGxlZy46IDIzOC8yMDE1KSA8L3BhcmFncmFwaD4KICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICAgICAgPGVudHJ5PgogICAgICAgICAgICAgICAgICAgICAgICA8YWN0IGNsYXNzQ29kZT0iQUNUIiBtb29kQ29kZT0iREVGIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjEwLjIwLjEuMjAiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC40LjUxIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aWQgbnVsbEZsYXZvcj0iTkEiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjb2RlIGNvZGU9IjQ4NzY4LTYiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjYuMSIgZGlzcGxheU5hbWU9IlBheW1lbnQgc291cmNlIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGV4dD48cmVmZXJlbmNlIHZhbHVlPSIjQUNUXzIiLz48L3RleHQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3RhdHVzQ29kZSBjb2RlPSJjb21wbGV0ZWQiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxlbnRyeVJlbGF0aW9uc2hpcCB0eXBlQ29kZT0iQ09NUCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGFjdCBjbGFzc0NvZGU9IkFDVCIgbW9vZENvZGU9IkVWTiI+IDwhLS0gVXByYXduaWVuaWUgZG9kYXRrb3dlIC0tPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4xMC4yMC4xLjI2Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC40LjYxIi8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpZCBudWxsRmxhdm9yPSJOQSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y29kZSBjb2RlPSJQVUJMSUNQT0wiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjUuNCI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cXVhbGlmaWVyPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxuYW1lIGNvZGU9IlJMVUQiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy41LjEiIGRpc3BsYXlOYW1lPSJSZWZ1bmRhY2phIGxla8OzdyB3eW5pa2FqxIVjYSB6IHVwcmF3bmllxYQgZG9kYXRrb3d5Y2giLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dmFsdWUgY29kZT0iSUIiIGNvZGVTeXN0ZW09IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMS4zLjEiIGRpc3BsYXlOYW1lPSJJQiIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9xdWFsaWZpZXI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvY29kZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRleHQ+PHJlZmVyZW5jZSB2YWx1ZT0iI0FDVF8yIi8+PC90ZXh0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8c3RhdHVzQ29kZSBjb2RlPSJjb21wbGV0ZWQiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHBlcmZvcm1lciB0eXBlQ29kZT0iUFJGIj4gPCEtLSBEYW5lIHViZXpwaWVjenljaWVsYS9wxYJhdG5pa2EgLS0+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YXNzaWduZWRFbnRpdHk+CQkJCQkJCQkJCQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxpZCBkaXNwbGF5YWJsZT0idHJ1ZSIgZXh0ZW5zaW9uPSIwNyIgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjMuMSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9hc3NpZ25lZEVudGl0eT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9wZXJmb3JtZXI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxlbnRyeVJlbGF0aW9uc2hpcCB0eXBlQ29kZT0iUkVGUiI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8YWN0IGNsYXNzQ29kZT0iQUNUIiBtb29kQ29kZT0iRVZOIj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8dGVtcGxhdGVJZCByb290PSIyLjE2Ljg0MC4xLjExMzg4My4xMC4yMC4xLjE5Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRlbXBsYXRlSWQgcm9vdD0iMi4xNi44NDAuMS4xMTM4ODMuMy40NDI0LjEzLjEwLjQuNTMiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aWQgbnVsbEZsYXZvcj0iTkEiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y29kZSBudWxsRmxhdm9yPSJOQSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxlbnRyeVJlbGF0aW9uc2hpcCB0eXBlQ29kZT0iU1VCSiI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxzdWJzdGFuY2VBZG1pbmlzdHJhdGlvbiBjbGFzc0NvZGU9IlNCQURNIiBtb29kQ29kZT0iUFJNUyI+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aWQgZXh0ZW5zaW9uPSIyMzQ1Njc4LTEiIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4yLjcuMjAxLjIuMyIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNvbnN1bWFibGU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPG1hbnVmYWN0dXJlZFByb2R1Y3Q+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxtYW51ZmFjdHVyZWRNYXRlcmlhbCBudWxsRmxhdm9yPSJOQSIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvbWFudWZhY3R1cmVkUHJvZHVjdD4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvY29uc3VtYWJsZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9zdWJzdGFuY2VBZG1pbmlzdHJhdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2VudHJ5UmVsYXRpb25zaGlwPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9hY3Q+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZW50cnlSZWxhdGlvbnNoaXA+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxyZWZlcmVuY2UgdHlwZUNvZGU9IlJFRlIiPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGV4dGVybmFsRG9jdW1lbnQgY2xhc3NDb2RlPSJET0MiIG1vb2RDb2RlPSJFVk4iPiA8IS0tIEluZm9ybWFjamEgbyBkb2t1bWVuY2llIHBvdHdpZXJkemFqxIVjeW0gdXByYXduaWVuaWUgZG9kYXRrb3dlIC0tPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDx0ZW1wbGF0ZUlkIHJvb3Q9IjIuMTYuODQwLjEuMTEzODgzLjMuNDQyNC4xMy4xMC40LjU5Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPHRleHQ+TnIgbGVnLjogMjM0LzE5OTI8L3RleHQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2V4dGVybmFsRG9jdW1lbnQ+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvcmVmZXJlbmNlPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvYWN0PgogICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9lbnRyeVJlbGF0aW9uc2hpcD4KICAgICAgICAgICAgICAgICAgICAgICAgPC9hY3Q+CiAgICAgICAgICAgICAgICAgICAgPC9lbnRyeT4KICAgICAgICAgICAgICAgIDwvc2VjdGlvbj4KICAgICAgICAgICAgPC9jb21wb25lbnQ+CiAgICAgICAgPC9zdHJ1Y3R1cmVkQm9keT4KICAgIDwvY29tcG9uZW50Pgo8ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIiBJZD0ieG1sZHNpZy1iYzAxYjkyZi0xMjU5LTRmODUtODE4My04MDE4MGFiNTlkNWEiPgo8ZHM6U2lnbmVkSW5mbz4KPGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy9UUi8yMDAxL1JFQy14bWwtYzE0bi0yMDAxMDMxNSIvPgo8ZHM6U2lnbmF0dXJlTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI3JzYS1zaGExIi8+CjxkczpSZWZlcmVuY2UgSWQ9InhtbGRzaWctYmMwMWI5MmYtMTI1OS00Zjg1LTgxODMtODAxODBhYjU5ZDVhLXJlZjAiIFVSST0iIj4KPGRzOlRyYW5zZm9ybXM+CjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPgo8L2RzOlRyYW5zZm9ybXM+CjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPgo8ZHM6RGlnZXN0VmFsdWU+UWdMM1puQkJNTFBFSlIvUDlhbjhNREVPN3pzPTwvZHM6RGlnZXN0VmFsdWU+CjwvZHM6UmVmZXJlbmNlPgo8ZHM6UmVmZXJlbmNlIFR5cGU9Imh0dHA6Ly91cmkuZXRzaS5vcmcvMDE5MDMjU2lnbmVkUHJvcGVydGllcyIgVVJJPSIjeG1sZHNpZy1iYzAxYjkyZi0xMjU5LTRmODUtODE4My04MDE4MGFiNTlkNWEtc2lnbmVkcHJvcHMiPgo8ZHM6VHJhbnNmb3Jtcz4KPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLXhtbC1jMTRuLTIwMDEwMzE1Ii8+CjwvZHM6VHJhbnNmb3Jtcz4KPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNzaGExIi8+CjxkczpEaWdlc3RWYWx1ZT5wY0VHcEd2MTVMdktqNDMycHJwOXJ6YjVneG89PC9kczpEaWdlc3RWYWx1ZT4KPC9kczpSZWZlcmVuY2U+CjwvZHM6U2lnbmVkSW5mbz4KPGRzOlNpZ25hdHVyZVZhbHVlIElkPSJ4bWxkc2lnLWJjMDFiOTJmLTEyNTktNGY4NS04MTgzLTgwMTgwYWI1OWQ1YS1zaWd2YWx1ZSI+CmQ1bTFLMjF4alB4dTR6em5aYS9iK25TVFRjeDdoSWc2QUxzNnR3WFh4OStraXNiU2I1OS9kMnUrQmNKZjBadDA0WGhNc2FyZnFqUGsKdTE2Qm40aHVWaUZHckEwYnh5L1pEY2pXdVhNYURoL3ZZNXJHMWVXdWdQSmlJcmdSM2xrSThROVViYk5HUUtkd1BGVjQ1NElYMkZScwpHVlFseFZNQWxqM2JRbDBmY0pJPQo8L2RzOlNpZ25hdHVyZVZhbHVlPgo8ZHM6S2V5SW5mbz4KPGRzOlg1MDlEYXRhPgo8ZHM6WDUwOUNlcnRpZmljYXRlPgpNSUlFM3pDQ0FzZWdBd0lCQWdJSVk0d0JNRzI2RldBd0RRWUpLb1pJaHZjTkFRRU5CUUF3VkRFYk1Ca0dBMVVFQXd3U1EwTWdVREVnClUzVmlRMEVnVUc5a2NHbHpNUmd3RmdZRFZRUUxEQTlRTVNCSmJuUmxaM0poWTNscWJtVXhEakFNQmdOVkJBb01CVU5UU1U5YU1Rc3cKQ1FZRFZRUUdFd0pRVERBZUZ3MHhPVEF6TWpZd056STFNRGRhRncweU1UQXpNalV3TnpJMU1EZGFNSEF4R2pBWUJnTlZCQU1NRVVGawpZVzB4TURZZ1RHVmplbTVwWTNwNU1Sc3dHUVlEVlFRRkV4SlFSVk5GVERvZ09UZ3dOVEU1TURNeU5URXhHREFXQmdOVkJBc01EMUF4CklFbHVkR1ZuY21GamVXcHVaVEVPTUF3R0ExVUVDZ3dGUTFOSlQxb3hDekFKQmdOVkJBWVRBbEJNTUlHZk1BMEdDU3FHU0liM0RRRUIKQVFVQUE0R05BRENCaVFLQmdRQ3BZcHBvZXh1bUMxNTRGUXZLUDV6S1hLOUlPekRuTERxN09FZ3RmNTA4MkVnbjl4YzlKdFNHWDFxaQoyZ3I3cXV3UTh0NnEraE1IMm1VS3B0LytUeHhXYloyVE1YUEFndkd1WlJ3WnhYQlZUcUpzWlpGOFkxckFJdUV5UkZINWwyS3RMdC9jCldwd1AvZU9sQjU3eW5Eck03cTRsRWNwaUlDWHRnOGJ0U1RlNkZ3SURBUUFCbzRJQkd6Q0NBUmN3SFFZRFZSME9CQllFRkpaOXk2cCsKNHFiK3BKajdPVE9qMjczeFRvaGZNQXdHQTFVZEV3RUIvd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVVra1RKVkx1NlE5UVBENnY0NjdnNQo2enVOQmdvd1Z3WURWUjBmQkZBd1RqQk1vRXFnU0laR2FIUjBjRG92TDNkekxXbHVkQzF3TVM1amMybHZlaTVuYjNZdWNHd3ZZMk53Ck1TOWpjbXd2UTBOUU1VbHVkR1ZuY21GamVXcHVaVk4xWWtOQlVHOWtjR2x6TG1OeWJEQU9CZ05WSFE4QkFmOEVCQU1DQXVRd1hnWUQKVlIwbEJGY3dWUVlJS3dZQkJRVUhBd0lHQ0NzR0FRVUZCd01FQmdvckJnRUVBWUkzRkFJQ0Jnb3JCZ0VFQVlJM0NnTU1CZ29yQmdFRQpBWUkzQ2dNRUJna3Foa2lHOXk4QkFRVUdCeXNHQVFVQ0F3UUdCeXNHQVFVQ0F3VXdEUVlKS29aSWh2Y05BUUVOQlFBRGdnSUJBRlRJClZWczd4d3RLRDVHUnVhSnpaQ2kyVjJmZ1JUVTBMb1B1ZjV5L0EvZGlwNys4TkJ3SStmeFJZTG5VRldQUHQzVmFWWmxURGRJT2VSQ3QKVEZVd2tYL0R2STFNeUVDaGt6THRTQmNTMys1Sm1GVC9XVy82Y0RwamM5WFNnVE50UWxWblJoamtSR1ZxZE96RGhLdDdKT3lWSjI2ZgpVUTNnSFNNTTJ6Ni9kWDk4aXg1Lzhya3N2S3JUQWY4RFpzRXpzV0VVdEVubFBIa1pwdDduK0ZQVWVzQklpVjNiK0hPcE5TNCs4UnFvCnRLMldVK1lVdWJ2SFBKY1NPV1hFVHkxaDNJOE9PNmJrUkdBMk1YZ0J2eWN0L2Z3bUk5eXBlL0REZXV1TXhYbVhkZ2lpRW5UazhmK0YKZW95QXNLdDMzQXR0cktQcXdVWXNyV1ZzSnNCUCsvaFpmblpKaXF4b2lNLzZidVpVZTFic2twT0s5VTI2L3grMWQ5QzBMeTVISWpFeQpFRFFIZE1CZFp6OGtvUk9zV0NIYk94QU50a0svekNBRzNTbFJLR1BVVDhtZnllZFZ5N3V3SXo2WFhUWDE3czhuSDg4UE05enNxMnBqCjFMaVNuRkt0dm1DNGlvOFdPYjhTbTB0MUJlaWpUYWlQTnpNVCtOL01tQjRRclV3ekYzZ2JoSVJWVzUyeWwyRllNM3Y5alhkWVlQVXcKVHVHeU5EVDNLS3lJOU14RFpTM0JvUEFORzVnaHFqVG9tSnV1Mlp5eWp6ejhPL0p6a3lJeXFXRjhwTVVmSVk3WVhldXVIdW5kUE1USgpEb2Joc0RjTmdUbml5RkFvMCsvZjFRZFVOd3pmMGMxMzdEcXRXa2k4cG5YZm8xMXNhNEF1dnpzK2E0ckVEUldWYjJkYXBORWkKPC9kczpYNTA5Q2VydGlmaWNhdGU+CjxkczpYNTA5U3ViamVjdE5hbWU+Qz1QTCwgTz1DU0lPWiwgT1U9UDEgSW50ZWdyYWN5am5lLCBPSUQuMi41LjQuNT1QRVNFTDogOTgwNTE5MDMyNTEsIENOPUFkYW0xMDYgTGVjem5pY3p5PC9kczpYNTA5U3ViamVjdE5hbWU+CjxkczpYNTA5SXNzdWVyU2VyaWFsPgo8ZHM6WDUwOUlzc3Vlck5hbWU+Qz1QTCxPPUNTSU9aLE9VPVAxIEludGVncmFjeWpuZSxDTj1DQyBQMSBTdWJDQSBQb2RwaXM8L2RzOlg1MDlJc3N1ZXJOYW1lPgo8ZHM6WDUwOVNlcmlhbE51bWJlcj43MTczMTA5NjE0MDA1MzI3MjAwPC9kczpYNTA5U2VyaWFsTnVtYmVyPgo8L2RzOlg1MDlJc3N1ZXJTZXJpYWw+CjwvZHM6WDUwOURhdGE+CjwvZHM6S2V5SW5mbz4KPGRzOk9iamVjdD48eGFkZXM6UXVhbGlmeWluZ1Byb3BlcnRpZXMgeG1sbnM6eGFkZXM9Imh0dHA6Ly91cmkuZXRzaS5vcmcvMDE5MDMvdjEuMy4yIyIgeG1sbnM6eGFkZXMxNDE9Imh0dHA6Ly91cmkuZXRzaS5vcmcvMDE5MDMvdjEuNC4xIyIgVGFyZ2V0PSIjeG1sZHNpZy1iYzAxYjkyZi0xMjU5LTRmODUtODE4My04MDE4MGFiNTlkNWEiPjx4YWRlczpTaWduZWRQcm9wZXJ0aWVzIElkPSJ4bWxkc2lnLWJjMDFiOTJmLTEyNTktNGY4NS04MTgzLTgwMTgwYWI1OWQ1YS1zaWduZWRwcm9wcyI+PHhhZGVzOlNpZ25lZFNpZ25hdHVyZVByb3BlcnRpZXM+PHhhZGVzOlNpZ25pbmdUaW1lPjIwMTktMDctMjdUMDk6MTU6NDEuMjY2KzAyOjAwPC94YWRlczpTaWduaW5nVGltZT48eGFkZXM6U2lnbmluZ0NlcnRpZmljYXRlPjx4YWRlczpDZXJ0Pjx4YWRlczpDZXJ0RGlnZXN0PjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxkczpEaWdlc3RWYWx1ZT55d0R2SjRFTUs3L05PcFFWWW9Jc2dKQ2swSVE9PC9kczpEaWdlc3RWYWx1ZT48L3hhZGVzOkNlcnREaWdlc3Q+PHhhZGVzOklzc3VlclNlcmlhbD48ZHM6WDUwOUlzc3Vlck5hbWU+Qz1QTCxPPUNTSU9aLE9VPVAxIEludGVncmFjeWpuZSxDTj1DQyBQMSBTdWJDQSBQb2RwaXM8L2RzOlg1MDlJc3N1ZXJOYW1lPjxkczpYNTA5U2VyaWFsTnVtYmVyPjcxNzMxMDk2MTQwMDUzMjcyMDA8L2RzOlg1MDlTZXJpYWxOdW1iZXI+PC94YWRlczpJc3N1ZXJTZXJpYWw+PC94YWRlczpDZXJ0Pjx4YWRlczpDZXJ0Pjx4YWRlczpDZXJ0RGlnZXN0PjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxkczpEaWdlc3RWYWx1ZT5ObFFVaFJUcEtTT0kzZ3RMdUdrQmFRaU5xbWM9PC9kczpEaWdlc3RWYWx1ZT48L3hhZGVzOkNlcnREaWdlc3Q+PHhhZGVzOklzc3VlclNlcmlhbD48ZHM6WDUwOUlzc3Vlck5hbWU+Qz1QTCxPPUNTSU9aLE9VPVAxIEludGVncmFjeWpuZSxDTj1DQyBQMSBSb290Q0E8L2RzOlg1MDlJc3N1ZXJOYW1lPjxkczpYNTA5U2VyaWFsTnVtYmVyPjIwNTQ2ODczNTQyOTc5MzAzNTQ8L2RzOlg1MDlTZXJpYWxOdW1iZXI+PC94YWRlczpJc3N1ZXJTZXJpYWw+PC94YWRlczpDZXJ0Pjx4YWRlczpDZXJ0Pjx4YWRlczpDZXJ0RGlnZXN0PjxkczpEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPjxkczpEaWdlc3RWYWx1ZT5VRlB1dVUzaHBCMTNCVUsyR3JNWS9PNDVwVk09PC9kczpEaWdlc3RWYWx1ZT48L3hhZGVzOkNlcnREaWdlc3Q+PHhhZGVzOklzc3VlclNlcmlhbD48ZHM6WDUwOUlzc3Vlck5hbWU+Qz1QTCxPPUNTSU9aLE9VPVAxIEludGVncmFjeWpuZSxDTj1DQyBQMSBSb290Q0E8L2RzOlg1MDlJc3N1ZXJOYW1lPjxkczpYNTA5U2VyaWFsTnVtYmVyPjc1ODE4Nzk3MjA2MzA2NjAyMjY8L2RzOlg1MDlTZXJpYWxOdW1iZXI+PC94YWRlczpJc3N1ZXJTZXJpYWw+PC94YWRlczpDZXJ0PjwveGFkZXM6U2lnbmluZ0NlcnRpZmljYXRlPjwveGFkZXM6U2lnbmVkU2lnbmF0dXJlUHJvcGVydGllcz48L3hhZGVzOlNpZ25lZFByb3BlcnRpZXM+PC94YWRlczpRdWFsaWZ5aW5nUHJvcGVydGllcz48L2RzOk9iamVjdD4KPC9kczpTaWduYXR1cmU+PC9DbGluaWNhbERvY3VtZW50Pg==";

        // String detectedCharset = charset(text, new String[] { "UTF-8", "UTF-16", "ISO-8859-1" });

        // System.out.println("detectedCharset " + detectedCharset);

        // byte[] bytes = text.getBytes("UTF-8");
        // System.out.println(new String(bytes, Charset.forName("UTF-8")));

        // System.out.println(s);
        // s.getBytes(Charset.forName("UTF-8")).encodeBase64().toString();
        // byte[] encodeBase64 = Base64.encodeBase64(s.getBytes("UTF-8"));
        // System.out.println(new String(encodeBase64, Charset.forName("UTF-8")));
        // recepta.setTresc(IOUtils.readBytesFromStream(inputStream));
        // recepta.setTresc("ABC".getBytes("UTF-8"));
        // recepta.setTresc(text.getBytes("ISO-8859-1"));
        // recepta.setTresc(s.getBytes("UTF-8"));
        // recepta.setTresc(encodeBase64);
        // String content = getContent();
        // System.out.println(content.getBytes());
        // byte[] bytes = Base64.encodeBase64(content.getBytes());
        // String gzi = new String(bytes);
        // System.out.println(gzi);

        // recepta.setTresc(content.getBytes("UTF-8"));
        recepta.setTresc(IOUtils.readBytesFromStream(inputStream));
        recepty.getRecepta().add(recepta);

        IdentyfikatorZadaniaMT identyfikatorZadania = new IdentyfikatorZadaniaMT();
        identyfikatorZadania.setIdZadania(UUID.randomUUID().toString());

        pakietRecept.setRecepty(recepty);
        // pakietRecept.setIdentyfikatorZadania(identyfikatorZadania);
        zapisPakietuReceptRequest.setPakietRecept(pakietRecept);

        return zapisPakietuReceptRequest;
    }

    public static String charset(String value, String charsets[]) throws Exception {
        String probe = StandardCharsets.UTF_8.name();
        for(String c : charsets) {
            Charset charset = Charset.forName(c);
            if(charset != null) {
                if(value.equals(convert(convert(value, charset.name(), probe), probe, charset.name()))) {
                    return c;
                }
            }
        }
        return StandardCharsets.UTF_8.name();
    }

    public static String convert(String value, String fromEncoding, String toEncoding) throws Exception {
        return new String(value.getBytes(fromEncoding), toEncoding);
    }

    private String getContent() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\"?><?xml-stylesheet href=\"CDA_PL_IG_1.3.1.xsl\" type=\"text/xsl\"?><ClinicalDocument xmlns=\"urn:hl7-org:v3\" xmlns:extPL=\"http://www.csioz.gov.pl/xsd/extPL/r2\" xmlns:pharm=\"urn:ihe:pharm\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:type=\"extPL:ClinicalDocument\">\n" +
                "    <!-- Dokument recepty na lek OTC-->\n" +
                "    <typeId extension=\"POCD_HD000040\" root=\"2.16.840.1.113883.1.3\"/>\n" +
                "    <templateId root=\"1.3.6.1.4.1.19376.1.9.1.1.1\"/>\n" +
                "    <templateId root=\"1.3.6.1.4.1.19376.1.5.3.1.1.1\"/>\n" +
                "    <templateId extension=\"1.3.1\" root=\"2.16.840.1.113883.3.4424.13.10.1.3\"/>\n" +
                "    <id displayable=\"true\" extension=\"3CC1EAFA706C4348BA4471\" root=\"2.16.840.1.113883.3.4424.2.7.201.2.1\"/>\n" +
                "    <code code=\"57833-6\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\" displayName=\"Prescription for medication Document\">\n" +
                "        <translation code=\"04.01\" codeSystem=\"2.16.840.1.113883.3.4424.11.1.32\" codeSystemName=\"KLAS_DOK_P1\" displayName=\"Recepta\">\n" +
                "            <qualifier>\n" +
                "                <name code=\"KDLEK\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" codeSystemName=\"PolskieKlasyfikatoryHL7v3\" displayName=\"Kategoria dostępności leku\"/>\n" +
                "                <value code=\"Rp\" codeSystem=\"2.16.840.1.113883.3.4424.11.1.25\"/>\n" +
                "            </qualifier>\n" +
                "            <qualifier>\n" +
                "                <name code=\"RLEK\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" codeSystemName=\"PolskieKlasyfikatoryHL7v3\" displayName=\"Rodzaj leku\"/>\n" +
                "                <value code=\"G\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" displayName=\"Lek gotowy\"/>\n" +
                "            </qualifier>\n" +
                "            <qualifier>\n" +
                "                <name code=\"TWREC\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" codeSystemName=\"PolskieKlasyfikatoryHL7v3\" displayName=\"Tryb wystawienia recepty\"/>\n" +
                "                <value code=\"Z\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" displayName=\"Zwykła\"/>\n" +
                "            </qualifier>\n" +
                "            <qualifier>\n" +
                "                <name code=\"TRREC\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" codeSystemName=\"PolskieKlasyfikatoryHL7v3\" displayName=\"Tryb realizacji recepty\"/>\n" +
                "                <value code=\"Z\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" displayName=\"Zwykły\"/>\n" +
                "            </qualifier>\n" +
                "        </translation>\n" +
                "    </code>\n" +
                "    <title>Recepta</title>\n" +
                "    <effectiveTime value=\"20190727091540\"/>\n" +
                "    <confidentialityCode code=\"N\" codeSystem=\"2.16.840.1.113883.5.25\"/>\n" +
                "    <languageCode code=\"pl-PL\"/>\n" +
                "    <setId extension=\"432231\" root=\"2.16.840.1.113883.3.4424.7.2.2\"/>\n" +
                "    <versionNumber value=\"1\"/>\n" +
                "    <recordTarget>\n" +
                "        <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.23\"/>\n" +
                "        <patientRole>\n" +
                "            <id displayable=\"false\" extension=\"12345\" root=\"2.16.840.1.113883.3.4424.2.7.0.17.1\"/>\n" +
                "            <id displayable=\"true\" extension=\"64010595888\" root=\"2.16.840.1.113883.3.4424.1.1.616\"/>\n" +
                "            <addr>\n" +
                "                <country>Polska</country>\n" +
                "                <postalCode postCity=\"Piaseczno\" xsi:type=\"extPL:adxp.postalCode\">03-134</postalCode>\n" +
                "                <city>Warszawa</city>\n" +
                "                <streetName>Odkryta</streetName>\n" +
                "                <houseNumber>41</houseNumber>\n" +
                "                <unitID>12</unitID>\n" +
                "                <censusTract>TERYT SIMC: 987654</censusTract>\n" +
                "            </addr>\n" +
                "            <patient>\n" +
                "                <name>\n" +
                "                    <given>Jan</given>\n" +
                "                    <given>Franciszek</given>\n" +
                "                    <family>Kowalski</family>\n" +
                "                </name>\n" +
                "                <administrativeGenderCode code=\"M\" codeSystem=\"2.16.840.1.113883.5.1\"/>\n" +
                "                <birthTime value=\"19620915\"/>\n" +
                "            </patient>\n" +
                "        </patientRole>\n" +
                "    </recordTarget>\n" +
                "    <author>\n" +
                "        <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.82\"/>\n" +
                "        <functionCode code=\"LEK\" codeSystem=\"2.16.840.1.113883.3.4424.11.3.18\" displayName=\"Lekarz\"/>\n" +
                "        <time value=\"20171012\"/>\n" +
                "        <assignedAuthor>\n" +
                "            <id displayable=\"true\" extension=\"7391208\" root=\"2.16.840.1.113883.3.4424.1.6.2\"/>\n" +
                "            <assignedPerson>\n" +
                "                <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.1\"/>\n" +
                "                <name>\n" +
                "                    <given>Adam</given>\n" +
                "                    <family>Kowalski</family>\n" +
                "                </name>\n" +
                "            </assignedPerson>\n" +
                "            <representedOrganization>\n" +
                "                <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.17\"/>\n" +
                "                <id displayable=\"true\" extension=\"000000926578-001\" root=\"2.16.840.1.113883.3.4424.2.3.2\"/>\n" +
                "                <name>Poradnia POZ</name>\n" +
                "                <telecom use=\"PUB\" value=\"tel:22-1111123\"/>\n" +
                "                <addr>\n" +
                "                    <postalCode>00-184</postalCode>\n" +
                "                    <city>Warszawa</city>\n" +
                "                    <streetName>ul. Dubois</streetName>\n" +
                "                    <houseNumber>5A</houseNumber>\n" +
                "                </addr>\n" +
                "                <asOrganizationPartOf>\n" +
                "                    <wholeOrganization>\n" +
                "\t\t\t\t\t\t<!-- Regon przedsiębiorstwa -->\n" +
                "                        <id displayable=\"true\" extension=\"84094783500004\" root=\"2.16.840.1.113883.3.4424.2.2.2\"/>\n" +
                "                        <asOrganizationPartOf>\n" +
                "\t\t\t\t\t\t<!-- podmiot - nr ksiegi + regon podmiotu -->\n" +
                "                            <wholeOrganization>\n" +
                "                                <id displayable=\"true\" extension=\"000000926578\" root=\"2.16.840.1.113883.3.4424.2.3.1\"/>\n" +
                "                                <!-- <id extension=\"123456789\" root=\"2.16.840.1.113883.3.4424.2.2.1\" displayable=\"true\"/> -->\n" +
                "                            </wholeOrganization>\n" +
                "                        </asOrganizationPartOf>\n" +
                "                    </wholeOrganization>\n" +
                "                </asOrganizationPartOf>\n" +
                "            </representedOrganization>\n" +
                "        </assignedAuthor>\n" +
                "    </author>\n" +
                "    <custodian>\n" +
                "        <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.20\"/>\n" +
                "        <assignedCustodian>\n" +
                "            <representedCustodianOrganization>\n" +
                "                <id assigningAuthorityName=\"CSIOZ\" displayable=\"false\" root=\"2.16.840.1.113883.3.4424\"/>\n" +
                "            </representedCustodianOrganization>\n" +
                "        </assignedCustodian>\n" +
                "    </custodian>\n" +
                "    <legalAuthenticator>\n" +
                "        <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.6\"/>\n" +
                "        <time value=\"20171012\"/>\n" +
                "        <signatureCode code=\"S\"/>\n" +
                "        <assignedEntity>\n" +
                "            <id displayable=\"true\" extension=\"7391208\" root=\"2.16.840.1.113883.3.4424.1.6.2\"/>\n" +
                "        </assignedEntity>\n" +
                "    </legalAuthenticator>\n" +
                "    <component>\n" +
                "        <templateId root=\"2.16.840.1.113883.3.4424.13.10.2.25\"/>\n" +
                "        <structuredBody>\n" +
                "            <component>\n" +
                "                <section>\n" +
                "                    <templateId root=\"1.3.6.1.4.1.19376.1.9.1.2.1\"/>\n" +
                "                    <templateId root=\"2.16.840.1.113883.3.4424.13.10.3.4\"/>\n" +
                "                    <id extension=\"4321\" root=\"2.16.840.1.113883.3.4424.2.7.201.2.4\"/>\n" +
                "                    <code code=\"57828-6\" codeSystem=\"2.16.840.1.113883.6.1\" codeSystemName=\"LOINC\" displayName=\"Prescriptions\"/>\n" +
                "                    <title>Rp.</title>\n" +
                "                    <text>\n" +
                "                        <paragraph ID=\"SBADM_1\">\n" +
                "                            Zofran <br/>\n" +
                "                            1 op. po 60 tabl.<br/>\n" +
                "                            Odpłatność: 100%<br/>\n" +
                "                            D.S. 1 x 1 tabl. rano\n" +
                "                        </paragraph>\n" +
                "                    </text>\n" +
                "                    <entry>\n" +
                "                        <substanceAdministration classCode=\"SBADM\" moodCode=\"INT\">\n" +
                "                            <templateId root=\"1.3.6.1.4.1.19376.1.9.1.3.2\"/>\n" +
                "                            <templateId root=\"2.16.840.1.113883.10.20.1.24\"/>\n" +
                "                            <templateId root=\"1.3.6.1.4.1.19376.1.5.3.1.4.7\"/>\n" +
                "                            <templateId root=\"1.3.6.1.4.1.19376.1.9.1.3.6\"/>\n" +
                "                            <templateId root=\"1.3.6.1.4.1.19376.1.5.3.1.4.7.1\"/>\n" +
                "                            <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.3\"/>\n" +
                "                            <id extension=\"3CC1EAFA706C4348BA4471-1\" root=\"2.16.840.1.113883.3.4424.2.7.201.2.3\"/>\n" +
                "                            <text>\n" +
                "                                <reference value=\"#SBADM_1\"/>\n" +
                "                            </text>\n" +
                "                            <statusCode code=\"completed\"/>\n" +
                "                            <effectiveTime xsi:type=\"IVL_TS\">\n" +
                "                                <low value=\"20171012\"/>\n" +
                "                                <high nullFlavor=\"NA\"/>\n" +
                "                            </effectiveTime>\n" +
                "                            <repeatNumber value=\"1\"/>\n" +
                "                            <consumable>\n" +
                "                                <manufacturedProduct>\n" +
                "                                    <templateId root=\"2.16.840.1.113883.10.20.1.53\"/>\n" +
                "                                    <templateId root=\"1.3.6.1.4.1.19376.1.5.3.1.4.7.2\"/>\n" +
                "                                    <manufacturedMaterial>\n" +
                "                                        <templateId root=\"1.3.6.1.4.1.19376.1.9.1.3.1\"/>\n" +
                "                                        <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.54\"/>\n" +
                "                                        <code code=\"900000014\" codeSystem=\"2.16.840.1.113883.3.4424.6.1\" displayName=\"Zofran\"/>\n" +
                "                                        <name>Zofran</name>\n" +
                "                                        <pharm:asContent classCode=\"CONT\">\n" +
                "                                            <pharm:containerPackagedMedicine classCode=\"CONT\" determinerCode=\"INSTANCE\">\n" +
                "                                                <pharm:code code=\"09909991023652\" codeSystem=\"1.3.160\" codeSystemName=\"GS1\"/>\n" +
                "                                                <pharm:name>Zorfan</pharm:name>\n" +
                "                                                <pharm:formCode code=\"30066000\" codeSystem=\"0.4.0.127.0.16.1.1.2.1\" displayName=\"Tablet container\"/>\n" +
                "                                                <pharm:capacityQuantity value=\"60\"/>\n" +
                "                                            </pharm:containerPackagedMedicine>\n" +
                "                                        </pharm:asContent>\n" +
                "                                    </manufacturedMaterial>\n" +
                "                                </manufacturedProduct>\n" +
                "                            </consumable>\n" +
                "                            <entryRelationship typeCode=\"COMP\">\n" +
                "                                <supply classCode=\"SPLY\" moodCode=\"RQO\">\n" +
                "                                    <templateId root=\"1.3.6.1.4.1.19376.1.9.1.3.8\"/>\n" +
                "                                    <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.55\"/>\n" +
                "                                    <effectiveTime value=\"20190727091540\"/>\n" +
                "                                    <independentInd value=\"false\"/>\n" +
                "                                    <quantity value=\"1\"/>\n" +
                "                                    <product>\n" +
                "                                        <manufacturedProduct>\n" +
                "                                            <manufacturedLabeledDrug>\n" +
                "                                                <code code=\"09909991023652\" codeSystem=\"1.3.160\" codeSystemName=\"GS1\" displayName=\"Polocard 150mg (60 tabl.)\"/>\n" +
                "                                            </manufacturedLabeledDrug>\n" +
                "                                        </manufacturedProduct>\n" +
                "                                    </product>\n" +
                "                                </supply>\n" +
                "                            </entryRelationship>\n" +
                "                        </substanceAdministration>\n" +
                "                    </entry>\n" +
                "                </section>\n" +
                "            </component>\n" +
                "            <component>\n" +
                "                <section>\n" +
                "                    <templateId root=\"2.16.840.1.113883.10.20.1.9\"/>\n" +
                "                    <templateId root=\"1.3.6.1.4.1.19376.1.5.3.1.1.5.3.7\"/>\n" +
                "                    <templateId root=\"2.16.840.1.113883.3.4424.13.10.3.69\"/>\n" +
                "                    <code code=\"48768-6\" codeSystem=\"2.16.840.1.113883.6.1\"/>\n" +
                "                    <title>Dane o ubezpieczeniu i uprawnieniach</title>\n" +
                "                    <text>\n" +
                "                        <paragraph ID=\"ACT_2\"> Oddział NFZ: 07 <br/> Uprawnienia dodatkowe: ZK (Nr leg.: 238/2015) </paragraph>\n" +
                "                    </text>\n" +
                "                    <entry>\n" +
                "                        <act classCode=\"ACT\" moodCode=\"DEF\">\n" +
                "                            <templateId root=\"2.16.840.1.113883.10.20.1.20\"/>\n" +
                "                            <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.51\"/>\n" +
                "                            <id nullFlavor=\"NA\"/>\n" +
                "                            <code code=\"48768-6\" codeSystem=\"2.16.840.1.113883.6.1\" displayName=\"Payment source\"/>\n" +
                "                            <text><reference value=\"#ACT_2\"/></text>\n" +
                "                            <statusCode code=\"completed\"/>\n" +
                "                            <entryRelationship typeCode=\"COMP\">\n" +
                "                                <act classCode=\"ACT\" moodCode=\"EVN\"> <!-- Uprawnienie dodatkowe -->\n" +
                "                                    <templateId root=\"2.16.840.1.113883.10.20.1.26\"/>\n" +
                "                                    <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.61\"/>\n" +
                "                                    <id nullFlavor=\"NA\"/>\n" +
                "                                    <code code=\"PUBLICPOL\" codeSystem=\"2.16.840.1.113883.5.4\">\n" +
                "                                        <qualifier>\n" +
                "                                            <name code=\"RLUD\" codeSystem=\"2.16.840.1.113883.3.4424.13.5.1\" displayName=\"Refundacja leków wynikająca z uprawnień dodatkowych\"/>\n" +
                "                                            <value code=\"IB\" codeSystem=\"2.16.840.1.113883.3.4424.11.3.1\" displayName=\"IB\"/>\n" +
                "                                        </qualifier>\n" +
                "                                    </code>\n" +
                "                                    <text><reference value=\"#ACT_2\"/></text>\n" +
                "                                    <statusCode code=\"completed\"/>\n" +
                "                                    <performer typeCode=\"PRF\"> <!-- Dane ubezpieczyciela/płatnika -->\n" +
                "                                        <assignedEntity>\n" +
                "                                            <id displayable=\"true\" extension=\"07\" root=\"2.16.840.1.113883.3.4424.3.1\"/>\n" +
                "                                        </assignedEntity>\n" +
                "                                    </performer>\n" +
                "                                    <entryRelationship typeCode=\"REFR\">\n" +
                "                                        <act classCode=\"ACT\" moodCode=\"EVN\">\n" +
                "                                            <templateId root=\"2.16.840.1.113883.10.20.1.19\"/>\n" +
                "                                            <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.53\"/>\n" +
                "                                            <id nullFlavor=\"NA\"/>\n" +
                "                                            <code nullFlavor=\"NA\"/>\n" +
                "                                            <entryRelationship typeCode=\"SUBJ\">\n" +
                "                                                <substanceAdministration classCode=\"SBADM\" moodCode=\"PRMS\">\n" +
                "                                                    <id extension=\"2345678-1\" root=\"2.16.840.1.113883.3.4424.2.7.201.2.3\"/>\n" +
                "                                                    <consumable>\n" +
                "                                                        <manufacturedProduct>\n" +
                "                                                            <manufacturedMaterial nullFlavor=\"NA\"/>\n" +
                "                                                        </manufacturedProduct>\n" +
                "                                                    </consumable>\n" +
                "                                                </substanceAdministration>\n" +
                "                                            </entryRelationship>\n" +
                "                                        </act>\n" +
                "                                    </entryRelationship>\n" +
                "                                    <reference typeCode=\"REFR\">\n" +
                "                                        <externalDocument classCode=\"DOC\" moodCode=\"EVN\"> <!-- Informacja o dokumencie potwierdzającym uprawnienie dodatkowe -->\n" +
                "                                            <templateId root=\"2.16.840.1.113883.3.4424.13.10.4.59\"/>\n" +
                "                                            <text>Nr leg.: 234/1992</text>\n" +
                "                                        </externalDocument>\n" +
                "                                    </reference>\n" +
                "                                </act>\n" +
                "                            </entryRelationship>\n" +
                "                        </act>\n" +
                "                    </entry>\n" +
                "                </section>\n" +
                "            </component>\n" +
                "        </structuredBody>\n" +
                "    </component>\n" +
                "<ds:Signature xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\" Id=\"xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a\">\n" +
                "<ds:SignedInfo>\n" +
                "<ds:CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/>\n" +
                "<ds:SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/>\n" +
                "<ds:Reference Id=\"xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a-ref0\" URI=\"\">\n" +
                "<ds:Transforms>\n" +
                "<ds:Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"/>\n" +
                "</ds:Transforms>\n" +
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\n" +
                "<ds:DigestValue>QgL3ZnBBMLPEJR/P9an8MDEO7zs=</ds:DigestValue>\n" +
                "</ds:Reference>\n" +
                "<ds:Reference Type=\"http://uri.etsi.org/01903#SignedProperties\" URI=\"#xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a-signedprops\">\n" +
                "<ds:Transforms>\n" +
                "<ds:Transform Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315\"/>\n" +
                "</ds:Transforms>\n" +
                "<ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/>\n" +
                "<ds:DigestValue>pcEGpGv15LvKj432prp9rzb5gxo=</ds:DigestValue>\n" +
                "</ds:Reference>\n" +
                "</ds:SignedInfo>\n" +
                "<ds:SignatureValue Id=\"xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a-sigvalue\">\n" +
                "d5m1K21xjPxu4zznZa/b+nSTTcx7hIg6ALs6twXXx9+kisbSb59/d2u+BcJf0Zt04XhMsarfqjPk\n" +
                "u16Bn4huViFGrA0bxy/ZDcjWuXMaDh/vY5rG1eWugPJiIrgR3lkI8Q9UbbNGQKdwPFV454IX2FRs\n" +
                "GVQlxVMAlj3bQl0fcJI=\n" +
                "</ds:SignatureValue>\n" +
                "<ds:KeyInfo>\n" +
                "<ds:X509Data>\n" +
                "<ds:X509Certificate>\n" +
                "MIIE3zCCAsegAwIBAgIIY4wBMG26FWAwDQYJKoZIhvcNAQENBQAwVDEbMBkGA1UEAwwSQ0MgUDEg\n" +
                "U3ViQ0EgUG9kcGlzMRgwFgYDVQQLDA9QMSBJbnRlZ3JhY3lqbmUxDjAMBgNVBAoMBUNTSU9aMQsw\n" +
                "CQYDVQQGEwJQTDAeFw0xOTAzMjYwNzI1MDdaFw0yMTAzMjUwNzI1MDdaMHAxGjAYBgNVBAMMEUFk\n" +
                "YW0xMDYgTGVjem5pY3p5MRswGQYDVQQFExJQRVNFTDogOTgwNTE5MDMyNTExGDAWBgNVBAsMD1Ax\n" +
                "IEludGVncmFjeWpuZTEOMAwGA1UECgwFQ1NJT1oxCzAJBgNVBAYTAlBMMIGfMA0GCSqGSIb3DQEB\n" +
                "AQUAA4GNADCBiQKBgQCpYppoexumC154FQvKP5zKXK9IOzDnLDq7OEgtf5082Egn9xc9JtSGX1qi\n" +
                "2gr7quwQ8t6q+hMH2mUKpt/+TxxWbZ2TMXPAgvGuZRwZxXBVTqJsZZF8Y1rAIuEyRFH5l2KtLt/c\n" +
                "WpwP/eOlB57ynDrM7q4lEcpiICXtg8btSTe6FwIDAQABo4IBGzCCARcwHQYDVR0OBBYEFJZ9y6p+\n" +
                "4qb+pJj7OTOj273xTohfMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUkkTJVLu6Q9QPD6v467g5\n" +
                "6zuNBgowVwYDVR0fBFAwTjBMoEqgSIZGaHR0cDovL3dzLWludC1wMS5jc2lvei5nb3YucGwvY2Nw\n" +
                "MS9jcmwvQ0NQMUludGVncmFjeWpuZVN1YkNBUG9kcGlzLmNybDAOBgNVHQ8BAf8EBAMCAuQwXgYD\n" +
                "VR0lBFcwVQYIKwYBBQUHAwIGCCsGAQUFBwMEBgorBgEEAYI3FAICBgorBgEEAYI3CgMMBgorBgEE\n" +
                "AYI3CgMEBgkqhkiG9y8BAQUGBysGAQUCAwQGBysGAQUCAwUwDQYJKoZIhvcNAQENBQADggIBAFTI\n" +
                "VVs7xwtKD5GRuaJzZCi2V2fgRTU0LoPuf5y/A/dip7+8NBwI+fxRYLnUFWPPt3VaVZlTDdIOeRCt\n" +
                "TFUwkX/DvI1MyEChkzLtSBcS3+5JmFT/WW/6cDpjc9XSgTNtQlVnRhjkRGVqdOzDhKt7JOyVJ26f\n" +
                "UQ3gHSMM2z6/dX98ix5/8rksvKrTAf8DZsEzsWEUtEnlPHkZpt7n+FPUesBIiV3b+HOpNS4+8Rqo\n" +
                "tK2WU+YUubvHPJcSOWXETy1h3I8OO6bkRGA2MXgBvyct/fwmI9ype/DDeuuMxXmXdgiiEnTk8f+F\n" +
                "eoyAsKt33AttrKPqwUYsrWVsJsBP+/hZfnZJiqxoiM/6buZUe1bskpOK9U26/x+1d9C0Ly5HIjEy\n" +
                "EDQHdMBdZz8koROsWCHbOxANtkK/zCAG3SlRKGPUT8mfyedVy7uwIz6XXTX17s8nH88PM9zsq2pj\n" +
                "1LiSnFKtvmC4io8WOb8Sm0t1BeijTaiPNzMT+N/MmB4QrUwzF3gbhIRVW52yl2FYM3v9jXdYYPUw\n" +
                "TuGyNDT3KKyI9MxDZS3BoPANG5ghqjTomJuu2Zyyjzz8O/JzkyIyqWF8pMUfIY7YXeuuHundPMTJ\n" +
                "DobhsDcNgTniyFAo0+/f1QdUNwzf0c137DqtWki8pnXfo11sa4Auvzs+a4rEDRWVb2dapNEi\n" +
                "</ds:X509Certificate>\n" +
                "<ds:X509SubjectName>C=PL, O=CSIOZ, OU=P1 Integracyjne, OID.2.5.4.5=PESEL: 98051903251, CN=Adam106 Leczniczy</ds:X509SubjectName>\n" +
                "<ds:X509IssuerSerial>\n" +
                "<ds:X509IssuerName>C=PL,O=CSIOZ,OU=P1 Integracyjne,CN=CC P1 SubCA Podpis</ds:X509IssuerName>\n" +
                "<ds:X509SerialNumber>7173109614005327200</ds:X509SerialNumber>\n" +
                "</ds:X509IssuerSerial>\n" +
                "</ds:X509Data>\n" +
                "</ds:KeyInfo>\n" +
                "<ds:Object><xades:QualifyingProperties xmlns:xades=\"http://uri.etsi.org/01903/v1.3.2#\" xmlns:xades141=\"http://uri.etsi.org/01903/v1.4.1#\" Target=\"#xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a\"><xades:SignedProperties Id=\"xmldsig-bc01b92f-1259-4f85-8183-80180ab59d5a-signedprops\"><xades:SignedSignatureProperties><xades:SigningTime>2019-07-27T09:15:41.266+02:00</xades:SigningTime><xades:SigningCertificate><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><ds:DigestValue>ywDvJ4EMK7/NOpQVYoIsgJCk0IQ=</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>C=PL,O=CSIOZ,OU=P1 Integracyjne,CN=CC P1 SubCA Podpis</ds:X509IssuerName><ds:X509SerialNumber>7173109614005327200</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><ds:DigestValue>NlQUhRTpKSOI3gtLuGkBaQiNqmc=</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>C=PL,O=CSIOZ,OU=P1 Integracyjne,CN=CC P1 RootCA</ds:X509IssuerName><ds:X509SerialNumber>2054687354297930354</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert><xades:Cert><xades:CertDigest><ds:DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"/><ds:DigestValue>UFPuuU3hpB13BUK2GrMY/O45pVM=</ds:DigestValue></xades:CertDigest><xades:IssuerSerial><ds:X509IssuerName>C=PL,O=CSIOZ,OU=P1 Integracyjne,CN=CC P1 RootCA</ds:X509IssuerName><ds:X509SerialNumber>7581879720630660226</ds:X509SerialNumber></xades:IssuerSerial></xades:Cert></xades:SigningCertificate></xades:SignedSignatureProperties></xades:SignedProperties></xades:QualifyingProperties></ds:Object>\n" +
                "</ds:Signature></ClinicalDocument>\n";
    }
}
