//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package pl.gov.csioz.xsd.extpl.r2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for adxp.postalCode complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="adxp.postalCode"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:hl7-org:v3}adxp.postalCode"&gt;
 *       &lt;attribute name="postCity" type="{urn:hl7-org:v3}st" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "adxp.postalCode")
public class AdxpPostalCode
        extends org.hl7.v3.AdxpPostalCode {

    @XmlAttribute(namespace = "http://www.w3.org/2001/XMLSchema-instance")
    private final String type = "extPL:adxp.postalCode";

    @XmlAttribute(name = "postCity")
    protected String postCity;

    /**
     * Gets the value of the postCity property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPostCity() {
        return postCity;
    }

    /**
     * Sets the value of the postCity property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPostCity(String value) {
        this.postCity = value;
    }

}
