//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.03 at 11:02:58 PM CEST 
//


package pl.gov.csioz.xsd.extpl.r2;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the pl.gov.csioz.xsd.extpl.r2 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.gov.csioz.xsd.extpl.r2
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AdxpPostalCode }
     */
    public AdxpPostalCode createAdxpPostalCode() {
        return new AdxpPostalCode();
    }

    /**
     * Create an instance of {@link InfrastructureRoot }
     */
    public InfrastructureRoot createInfrastructureRoot() {
        return new InfrastructureRoot();
    }

    /**
     * Create an instance of {@link PersonalRelationship }
     */
    public PersonalRelationship createPersonalRelationship() {
        return new PersonalRelationship();
    }

    /**
     * Create an instance of {@link Reimburser }
     */
    public Reimburser createReimburser() {
        return new Reimburser();
    }

    /**
     * Create an instance of {@link ReimbursementRelatedContract }
     */
    public ReimbursementRelatedContract createReimbursementRelatedContract() {
        return new ReimbursementRelatedContract();
    }

    /**
     * Create an instance of {@link RelatedPerson }
     */
    public RelatedPerson createRelatedPerson() {
        return new RelatedPerson();
    }

    /**
     * Create an instance of {@link BoundedByParticipation }
     */
    public BoundedByParticipation createBoundedByParticipation() {
        return new BoundedByParticipation();
    }

    /**
     * Create an instance of {@link BoundingParticipation }
     */
    public BoundingParticipation createBoundingParticipation() {
        return new BoundingParticipation();
    }

    /**
     * Create an instance of {@link ClinicalDocument }
     */
    public ClinicalDocument createClinicalDocument() {
        return new ClinicalDocument();
    }

    /**
     * Create an instance of {@link Patient }
     */
    public Patient createPatient() {
        return new Patient();
    }

    /**
     * Create an instance of {@link AssignedAuthor }
     */
    public AssignedAuthor createAssignedAuthor() {
        return new AssignedAuthor();
    }

}
